---
- hosts: all 
  become: true
  tasks:
    - name: Install  packages {{ item }} 
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_catch: yes 
      ignore_errors: true
      loop:
        - cset
        - ansible.core 
        - nettools
